name: GitHub Classroom Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6.4.6
      - uses: coursier/setup-action@v1.3.6
        with:
          apps: scala scalac
      - run: sh run-sanity-check.sh
